// src/components/Header/Header.tsx
import Box from '@mui/material/Box'
import { useTheme } from '@mui/material/styles'
import Link from '@mui/material/Link'
import StormkitLogoText from '~/assets/logos/stormkit-logo-text-h--white.svg'
import { ArrowRightAlt } from '@mui/icons-material'

interface Props {
  maxWidth?: string
}

let lastWidth: string = 'lg'

const links = [
  { path: '/#pricing', text: 'pricing' },
  { path: '/docs', text: 'docs' },
  { path: '/blog', text: 'blog' },
  { path: '/blog/whats-new', text: 'whats new?' },
  {
    path: 'https://app.stormkit.io',
    text: 'login',
    separator: true,
    icon: <ArrowRightAlt sx={{ fontSize: 20, ml: 0.5 }} />,
  },
]

export default function Header({ maxWidth = lastWidth }: Props) {
  const theme = useTheme()
  lastWidth = maxWidth

  return (
    <Box
      sx={{
        bgcolor: 'rgba(0,0,0,0.25)',
        boxShadow: 2,
        px: { xs: 1, md: 0 },
      }}
    >
      <Box
        maxWidth={maxWidth}
        sx={{
          m: 'auto',
          py: 2,
          px: maxWidth === 'none' ? { xs: 1, md: 4 } : 0,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
        }}
      >
        <Link href="/" sx={{ display: 'block', width: 130 }}>
          <img src={StormkitLogoText} alt="Stormkit Logo" width="100%" />
        </Link>
        <Box
          sx={{
            textTransform: 'uppercase',
            fontSize: 12.5,
            fontWeight: 600,
            display: 'flex',
            alignItems: 'center',
          }}
        >
          {links.map((link) => (
            <Link
              key={link.path}
              color={theme.palette.primary.contrastText}
              sx={{
                ml: 2,
                display: 'inline-flex',
                alignItems: 'center',
                textDecoration: 'none',
                opacity: 0.7,
                transition: 'opacity 0.25s ease-in-out',
                ':hover': { opacity: 1 },
                ...(link.separator
                  ? {
                      borderLeft: '1px solid rgba(255,255,255,0.3)',
                      pl: 2,
                    }
                  : {}),
              }}
              href={link.path}
            >
              {link.text}
              {link.icon}
            </Link>
          ))}
        </Box>
      </Box>
    </Box>
  )
}

// components/Header.vue
<template>
  <nav class="flex items-center justify-between flex-wrap text-gray-40">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <span class="flex items-center text-xl font-bold text-black">
        <img :src="skLogoWhite" class="mr-3 w-10" />
        Stormkit
      </span>
    </div>
    <div class="mobile-menu md:hidden">
      <button class="material-icons text-4xl" @click="toggleMenu">
        menu
      </button>
      <div v-if="displayMobileMenu" class="fixed inset-0 z-20 bg-white">
        <div class="text-right p-3">
          <button class="material-icons text-4xl" @click="toggleMenu">
            close
          </button>
        </div>
        <div class="text-sm text-xl pr-12 border-b border-gray-80">
          <a
            v-for="link in links"
            :key="link.path"
            :href="link.path"
            class="block text-gray-40 mb-4 px-4"
            >{{ link.text }}</a
          >
        </div>
        <div class="text-center p-3">
          <a href="https://app.stormkit.io/auth">
            <sk-button css-class="text-white border-white bg-pink-50 py-4">
              Login
            </sk-button>
          </a>
        </div>
      </div>
    </div>
    <div
      class="w-full block flex-grow lg:flex lg:items-center lg:w-auto absolute md:relative inset-0 md:inset-auto hidden md:block"
    >
      <div class="text-sm lg:flex-grow text-right text-base pr-12">
        <a
          v-for="link in links"
          :key="link.path"
          :href="link.path"
          class="inline-block transition duration-500 ease-in-out text-gray-40 hover:text-pink-50 mr-12 border-solid border-b-2 border-blue hover:border-pink-50"
          >{{ link.text }}</a
        >
      </div>
      <div>
        <a href="https://app.stormkit.io/auth">
          <sk-button css-class="bg-white text-black">Login</sk-button>
        </a>
      </div>
    </div>
  </nav>
</template>
<script>
import skLogoWhite from '../assets/images/stormkit-logo.svg'
import SkButton from '../components/Button'

export default {
  components: {
    SkButton
  },

  data: () => ({
    skLogoWhite,
    displayMobileMenu: false,
    links: [
      { text: 'Docs', path: '/docs' },
      { text: 'Blog', path: '/blog' },
      { text: 'Pricing', path: '/pricing' }
    ]
  }),

  methods: {
    toggleMenu() {
      this.displayMobileMenu = !this.displayMobileMenu
    }
  }
}
</script>
